/*
 * Generated by gdbus-codegen 2.60.7 from org.freedesktop.timedate1.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.timedate1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:MiniTimeDateTimedate1
 * @title: MiniTimeDateTimedate1
 * @short_description: Generated C code for the org.freedesktop.timedate1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.timedate1 ---- */

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_time_IN_ARG_usec_utc =
{
  {
    -1,
    (gchar *) "usec_utc",
    (gchar *) "x",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_time_IN_ARG_relative =
{
  {
    -1,
    (gchar *) "relative",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_time_IN_ARG_user_interaction =
{
  {
    -1,
    (gchar *) "user_interaction",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _mini_time_date_timedate1_method_info_set_time_IN_ARG_pointers[] =
{
  &_mini_time_date_timedate1_method_info_set_time_IN_ARG_usec_utc.parent_struct,
  &_mini_time_date_timedate1_method_info_set_time_IN_ARG_relative.parent_struct,
  &_mini_time_date_timedate1_method_info_set_time_IN_ARG_user_interaction.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _mini_time_date_timedate1_method_info_set_time =
{
  {
    -1,
    (gchar *) "SetTime",
    (GDBusArgInfo **) &_mini_time_date_timedate1_method_info_set_time_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-time",
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_timezone_IN_ARG_timezone =
{
  {
    -1,
    (gchar *) "timezone",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_timezone_IN_ARG_user_interaction =
{
  {
    -1,
    (gchar *) "user_interaction",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _mini_time_date_timedate1_method_info_set_timezone_IN_ARG_pointers[] =
{
  &_mini_time_date_timedate1_method_info_set_timezone_IN_ARG_timezone.parent_struct,
  &_mini_time_date_timedate1_method_info_set_timezone_IN_ARG_user_interaction.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _mini_time_date_timedate1_method_info_set_timezone =
{
  {
    -1,
    (gchar *) "SetTimezone",
    (GDBusArgInfo **) &_mini_time_date_timedate1_method_info_set_timezone_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-timezone",
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_local_rtc =
{
  {
    -1,
    (gchar *) "local_rtc",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_fix_system =
{
  {
    -1,
    (gchar *) "fix_system",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_user_interaction =
{
  {
    -1,
    (gchar *) "user_interaction",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_pointers[] =
{
  &_mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_local_rtc.parent_struct,
  &_mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_fix_system.parent_struct,
  &_mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_user_interaction.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _mini_time_date_timedate1_method_info_set_local_rtc =
{
  {
    -1,
    (gchar *) "SetLocalRTC",
    (GDBusArgInfo **) &_mini_time_date_timedate1_method_info_set_local_rtc_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-local-rtc",
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_ntp_IN_ARG_use_ntp =
{
  {
    -1,
    (gchar *) "use_ntp",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mini_time_date_timedate1_method_info_set_ntp_IN_ARG_user_interaction =
{
  {
    -1,
    (gchar *) "user_interaction",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _mini_time_date_timedate1_method_info_set_ntp_IN_ARG_pointers[] =
{
  &_mini_time_date_timedate1_method_info_set_ntp_IN_ARG_use_ntp.parent_struct,
  &_mini_time_date_timedate1_method_info_set_ntp_IN_ARG_user_interaction.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _mini_time_date_timedate1_method_info_set_ntp =
{
  {
    -1,
    (gchar *) "SetNTP",
    (GDBusArgInfo **) &_mini_time_date_timedate1_method_info_set_ntp_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-ntp",
  FALSE
};

static const GDBusMethodInfo * const _mini_time_date_timedate1_method_info_pointers[] =
{
  &_mini_time_date_timedate1_method_info_set_time.parent_struct,
  &_mini_time_date_timedate1_method_info_set_timezone.parent_struct,
  &_mini_time_date_timedate1_method_info_set_local_rtc.parent_struct,
  &_mini_time_date_timedate1_method_info_set_ntp.parent_struct,
  NULL
};

static const _ExtendedGDBusPropertyInfo _mini_time_date_timedate1_property_info_timezone =
{
  {
    -1,
    (gchar *) "Timezone",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "timezone",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _mini_time_date_timedate1_property_info_local_rtc =
{
  {
    -1,
    (gchar *) "LocalRTC",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "local-rtc",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _mini_time_date_timedate1_property_info_ntp =
{
  {
    -1,
    (gchar *) "NTP",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "ntp",
  FALSE,
  TRUE
};

static const GDBusPropertyInfo * const _mini_time_date_timedate1_property_info_pointers[] =
{
  &_mini_time_date_timedate1_property_info_timezone.parent_struct,
  &_mini_time_date_timedate1_property_info_local_rtc.parent_struct,
  &_mini_time_date_timedate1_property_info_ntp.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _mini_time_date_timedate1_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.timedate1",
    (GDBusMethodInfo **) &_mini_time_date_timedate1_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_mini_time_date_timedate1_property_info_pointers,
    NULL
  },
  "timedate1",
};


/**
 * mini_time_date_timedate1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
mini_time_date_timedate1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_mini_time_date_timedate1_interface_info.parent_struct;
}

/**
 * mini_time_date_timedate1_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #MiniTimeDateTimedate1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
mini_time_date_timedate1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "timezone");
  g_object_class_override_property (klass, property_id_begin++, "local-rtc");
  g_object_class_override_property (klass, property_id_begin++, "ntp");
  return property_id_begin - 1;
}



/**
 * MiniTimeDateTimedate1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link>.
 */

/**
 * MiniTimeDateTimedate1Iface:
 * @parent_iface: The parent interface.
 * @handle_set_local_rtc: Handler for the #MiniTimeDateTimedate1::handle-set-local-rtc signal.
 * @handle_set_ntp: Handler for the #MiniTimeDateTimedate1::handle-set-ntp signal.
 * @handle_set_time: Handler for the #MiniTimeDateTimedate1::handle-set-time signal.
 * @handle_set_timezone: Handler for the #MiniTimeDateTimedate1::handle-set-timezone signal.
 * @get_local_rtc: Getter for the #MiniTimeDateTimedate1:local-rtc property.
 * @get_ntp: Getter for the #MiniTimeDateTimedate1:ntp property.
 * @get_timezone: Getter for the #MiniTimeDateTimedate1:timezone property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link>.
 */

typedef MiniTimeDateTimedate1Iface MiniTimeDateTimedate1Interface;
G_DEFINE_INTERFACE (MiniTimeDateTimedate1, mini_time_date_timedate1, G_TYPE_OBJECT)

static void
mini_time_date_timedate1_default_init (MiniTimeDateTimedate1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * MiniTimeDateTimedate1::handle-set-time:
   * @object: A #MiniTimeDateTimedate1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_usec_utc: Argument passed by remote caller.
   * @arg_relative: Argument passed by remote caller.
   * @arg_user_interaction: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTime">SetTime()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mini_time_date_timedate1_complete_set_time() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-time",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MiniTimeDateTimedate1Iface, handle_set_time),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT64, G_TYPE_BOOLEAN, G_TYPE_BOOLEAN);

  /**
   * MiniTimeDateTimedate1::handle-set-timezone:
   * @object: A #MiniTimeDateTimedate1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_timezone: Argument passed by remote caller.
   * @arg_user_interaction: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTimezone">SetTimezone()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mini_time_date_timedate1_complete_set_timezone() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-timezone",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MiniTimeDateTimedate1Iface, handle_set_timezone),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_BOOLEAN);

  /**
   * MiniTimeDateTimedate1::handle-set-local-rtc:
   * @object: A #MiniTimeDateTimedate1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_local_rtc: Argument passed by remote caller.
   * @arg_fix_system: Argument passed by remote caller.
   * @arg_user_interaction: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-timedate1.SetLocalRTC">SetLocalRTC()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mini_time_date_timedate1_complete_set_local_rtc() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-local-rtc",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MiniTimeDateTimedate1Iface, handle_set_local_rtc),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN, G_TYPE_BOOLEAN, G_TYPE_BOOLEAN);

  /**
   * MiniTimeDateTimedate1::handle-set-ntp:
   * @object: A #MiniTimeDateTimedate1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_use_ntp: Argument passed by remote caller.
   * @arg_user_interaction: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-timedate1.SetNTP">SetNTP()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mini_time_date_timedate1_complete_set_ntp() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-ntp",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MiniTimeDateTimedate1Iface, handle_set_ntp),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN, G_TYPE_BOOLEAN);

  /* GObject properties for D-Bus properties: */
  /**
   * MiniTimeDateTimedate1:timezone:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-timedate1.Timezone">"Timezone"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("timezone", "Timezone", "Timezone", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * MiniTimeDateTimedate1:local-rtc:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-timedate1.LocalRTC">"LocalRTC"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("local-rtc", "LocalRTC", "LocalRTC", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * MiniTimeDateTimedate1:ntp:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-timedate1.NTP">"NTP"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("ntp", "NTP", "NTP", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * mini_time_date_timedate1_get_timezone: (skip)
 * @object: A #MiniTimeDateTimedate1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-timedate1.Timezone">"Timezone"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use mini_time_date_timedate1_dup_timezone() if on another thread.</warning>
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
mini_time_date_timedate1_get_timezone (MiniTimeDateTimedate1 *object)
{
  return MINI_TIME_DATE_TIMEDATE1_GET_IFACE (object)->get_timezone (object);
}

/**
 * mini_time_date_timedate1_dup_timezone: (skip)
 * @object: A #MiniTimeDateTimedate1.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-freedesktop-timedate1.Timezone">"Timezone"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
mini_time_date_timedate1_dup_timezone (MiniTimeDateTimedate1 *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "timezone", &value, NULL);
  return value;
}

/**
 * mini_time_date_timedate1_set_timezone: (skip)
 * @object: A #MiniTimeDateTimedate1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-timedate1.Timezone">"Timezone"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mini_time_date_timedate1_set_timezone (MiniTimeDateTimedate1 *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "timezone", value, NULL);
}

/**
 * mini_time_date_timedate1_get_local_rtc: (skip)
 * @object: A #MiniTimeDateTimedate1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-timedate1.LocalRTC">"LocalRTC"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
mini_time_date_timedate1_get_local_rtc (MiniTimeDateTimedate1 *object)
{
  return MINI_TIME_DATE_TIMEDATE1_GET_IFACE (object)->get_local_rtc (object);
}

/**
 * mini_time_date_timedate1_set_local_rtc: (skip)
 * @object: A #MiniTimeDateTimedate1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-timedate1.LocalRTC">"LocalRTC"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mini_time_date_timedate1_set_local_rtc (MiniTimeDateTimedate1 *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "local-rtc", value, NULL);
}

/**
 * mini_time_date_timedate1_get_ntp: (skip)
 * @object: A #MiniTimeDateTimedate1.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-timedate1.NTP">"NTP"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
mini_time_date_timedate1_get_ntp (MiniTimeDateTimedate1 *object)
{
  return MINI_TIME_DATE_TIMEDATE1_GET_IFACE (object)->get_ntp (object);
}

/**
 * mini_time_date_timedate1_set_ntp: (skip)
 * @object: A #MiniTimeDateTimedate1.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-timedate1.NTP">"NTP"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mini_time_date_timedate1_set_ntp (MiniTimeDateTimedate1 *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "ntp", value, NULL);
}

/**
 * mini_time_date_timedate1_call_set_time:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_usec_utc: Argument to pass with the method invocation.
 * @arg_relative: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTime">SetTime()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mini_time_date_timedate1_call_set_time_finish() to get the result of the operation.
 *
 * See mini_time_date_timedate1_call_set_time_sync() for the synchronous, blocking version of this method.
 */
void
mini_time_date_timedate1_call_set_time (
    MiniTimeDateTimedate1 *proxy,
    gint64 arg_usec_utc,
    gboolean arg_relative,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetTime",
    g_variant_new ("(xbb)",
                   arg_usec_utc,
                   arg_relative,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mini_time_date_timedate1_call_set_time_finish:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mini_time_date_timedate1_call_set_time().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mini_time_date_timedate1_call_set_time().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_time_finish (
    MiniTimeDateTimedate1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_time_sync:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_usec_utc: Argument to pass with the method invocation.
 * @arg_relative: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTime">SetTime()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mini_time_date_timedate1_call_set_time() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_time_sync (
    MiniTimeDateTimedate1 *proxy,
    gint64 arg_usec_utc,
    gboolean arg_relative,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetTime",
    g_variant_new ("(xbb)",
                   arg_usec_utc,
                   arg_relative,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_timezone:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_timezone: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTimezone">SetTimezone()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mini_time_date_timedate1_call_set_timezone_finish() to get the result of the operation.
 *
 * See mini_time_date_timedate1_call_set_timezone_sync() for the synchronous, blocking version of this method.
 */
void
mini_time_date_timedate1_call_set_timezone (
    MiniTimeDateTimedate1 *proxy,
    const gchar *arg_timezone,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetTimezone",
    g_variant_new ("(sb)",
                   arg_timezone,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mini_time_date_timedate1_call_set_timezone_finish:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mini_time_date_timedate1_call_set_timezone().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mini_time_date_timedate1_call_set_timezone().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_timezone_finish (
    MiniTimeDateTimedate1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_timezone_sync:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_timezone: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTimezone">SetTimezone()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mini_time_date_timedate1_call_set_timezone() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_timezone_sync (
    MiniTimeDateTimedate1 *proxy,
    const gchar *arg_timezone,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetTimezone",
    g_variant_new ("(sb)",
                   arg_timezone,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_local_rtc:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_local_rtc: Argument to pass with the method invocation.
 * @arg_fix_system: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetLocalRTC">SetLocalRTC()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mini_time_date_timedate1_call_set_local_rtc_finish() to get the result of the operation.
 *
 * See mini_time_date_timedate1_call_set_local_rtc_sync() for the synchronous, blocking version of this method.
 */
void
mini_time_date_timedate1_call_set_local_rtc (
    MiniTimeDateTimedate1 *proxy,
    gboolean arg_local_rtc,
    gboolean arg_fix_system,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetLocalRTC",
    g_variant_new ("(bbb)",
                   arg_local_rtc,
                   arg_fix_system,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mini_time_date_timedate1_call_set_local_rtc_finish:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mini_time_date_timedate1_call_set_local_rtc().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mini_time_date_timedate1_call_set_local_rtc().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_local_rtc_finish (
    MiniTimeDateTimedate1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_local_rtc_sync:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_local_rtc: Argument to pass with the method invocation.
 * @arg_fix_system: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetLocalRTC">SetLocalRTC()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mini_time_date_timedate1_call_set_local_rtc() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_local_rtc_sync (
    MiniTimeDateTimedate1 *proxy,
    gboolean arg_local_rtc,
    gboolean arg_fix_system,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetLocalRTC",
    g_variant_new ("(bbb)",
                   arg_local_rtc,
                   arg_fix_system,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_ntp:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_use_ntp: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetNTP">SetNTP()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mini_time_date_timedate1_call_set_ntp_finish() to get the result of the operation.
 *
 * See mini_time_date_timedate1_call_set_ntp_sync() for the synchronous, blocking version of this method.
 */
void
mini_time_date_timedate1_call_set_ntp (
    MiniTimeDateTimedate1 *proxy,
    gboolean arg_use_ntp,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetNTP",
    g_variant_new ("(bb)",
                   arg_use_ntp,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mini_time_date_timedate1_call_set_ntp_finish:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mini_time_date_timedate1_call_set_ntp().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mini_time_date_timedate1_call_set_ntp().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_ntp_finish (
    MiniTimeDateTimedate1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_call_set_ntp_sync:
 * @proxy: A #MiniTimeDateTimedate1Proxy.
 * @arg_use_ntp: Argument to pass with the method invocation.
 * @arg_user_interaction: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-timedate1.SetNTP">SetNTP()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mini_time_date_timedate1_call_set_ntp() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mini_time_date_timedate1_call_set_ntp_sync (
    MiniTimeDateTimedate1 *proxy,
    gboolean arg_use_ntp,
    gboolean arg_user_interaction,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetNTP",
    g_variant_new ("(bb)",
                   arg_use_ntp,
                   arg_user_interaction),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mini_time_date_timedate1_complete_set_time:
 * @object: A #MiniTimeDateTimedate1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTime">SetTime()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mini_time_date_timedate1_complete_set_time (
    MiniTimeDateTimedate1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * mini_time_date_timedate1_complete_set_timezone:
 * @object: A #MiniTimeDateTimedate1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-timedate1.SetTimezone">SetTimezone()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mini_time_date_timedate1_complete_set_timezone (
    MiniTimeDateTimedate1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * mini_time_date_timedate1_complete_set_local_rtc:
 * @object: A #MiniTimeDateTimedate1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-timedate1.SetLocalRTC">SetLocalRTC()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mini_time_date_timedate1_complete_set_local_rtc (
    MiniTimeDateTimedate1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * mini_time_date_timedate1_complete_set_ntp:
 * @object: A #MiniTimeDateTimedate1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-timedate1.SetNTP">SetNTP()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mini_time_date_timedate1_complete_set_ntp (
    MiniTimeDateTimedate1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * MiniTimeDateTimedate1Proxy:
 *
 * The #MiniTimeDateTimedate1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MiniTimeDateTimedate1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MiniTimeDateTimedate1Proxy.
 */

struct _MiniTimeDateTimedate1ProxyPrivate
{
  GData *qdata;
};

static void mini_time_date_timedate1_proxy_iface_init (MiniTimeDateTimedate1Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (MiniTimeDateTimedate1Proxy, mini_time_date_timedate1_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (MiniTimeDateTimedate1Proxy)
                         G_IMPLEMENT_INTERFACE (MINI_TIME_DATE_TYPE_TIMEDATE1, mini_time_date_timedate1_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (MiniTimeDateTimedate1Proxy, mini_time_date_timedate1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (MINI_TIME_DATE_TYPE_TIMEDATE1, mini_time_date_timedate1_proxy_iface_init))

#endif
static void
mini_time_date_timedate1_proxy_finalize (GObject *object)
{
  MiniTimeDateTimedate1Proxy *proxy = MINI_TIME_DATE_TIMEDATE1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (mini_time_date_timedate1_proxy_parent_class)->finalize (object);
}

static void
mini_time_date_timedate1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  info = (const _ExtendedGDBusPropertyInfo *) _mini_time_date_timedate1_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
mini_time_date_timedate1_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.freedesktop.timedate1: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
mini_time_date_timedate1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  info = (const _ExtendedGDBusPropertyInfo *) _mini_time_date_timedate1_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.freedesktop.timedate1", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) mini_time_date_timedate1_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
mini_time_date_timedate1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_mini_time_date_timedate1_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], MINI_TIME_DATE_TYPE_TIMEDATE1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MINI_TIME_DATE_TYPE_TIMEDATE1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
mini_time_date_timedate1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  MiniTimeDateTimedate1Proxy *proxy = MINI_TIME_DATE_TIMEDATE1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mini_time_date_timedate1_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mini_time_date_timedate1_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
mini_time_date_timedate1_proxy_get_timezone (MiniTimeDateTimedate1 *object)
{
  MiniTimeDateTimedate1Proxy *proxy = MINI_TIME_DATE_TIMEDATE1_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Timezone");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
mini_time_date_timedate1_proxy_get_local_rtc (MiniTimeDateTimedate1 *object)
{
  MiniTimeDateTimedate1Proxy *proxy = MINI_TIME_DATE_TIMEDATE1_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "LocalRTC");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
mini_time_date_timedate1_proxy_get_ntp (MiniTimeDateTimedate1 *object)
{
  MiniTimeDateTimedate1Proxy *proxy = MINI_TIME_DATE_TIMEDATE1_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "NTP");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
mini_time_date_timedate1_proxy_init (MiniTimeDateTimedate1Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = mini_time_date_timedate1_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, MINI_TIME_DATE_TYPE_TIMEDATE1_PROXY, MiniTimeDateTimedate1ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), mini_time_date_timedate1_interface_info ());
}

static void
mini_time_date_timedate1_proxy_class_init (MiniTimeDateTimedate1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = mini_time_date_timedate1_proxy_finalize;
  gobject_class->get_property = mini_time_date_timedate1_proxy_get_property;
  gobject_class->set_property = mini_time_date_timedate1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = mini_time_date_timedate1_proxy_g_signal;
  proxy_class->g_properties_changed = mini_time_date_timedate1_proxy_g_properties_changed;

  mini_time_date_timedate1_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (MiniTimeDateTimedate1ProxyPrivate));
#endif
}

static void
mini_time_date_timedate1_proxy_iface_init (MiniTimeDateTimedate1Iface *iface)
{
  iface->get_timezone = mini_time_date_timedate1_proxy_get_timezone;
  iface->get_local_rtc = mini_time_date_timedate1_proxy_get_local_rtc;
  iface->get_ntp = mini_time_date_timedate1_proxy_get_ntp;
}

/**
 * mini_time_date_timedate1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mini_time_date_timedate1_proxy_new_finish() to get the result of the operation.
 *
 * See mini_time_date_timedate1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
mini_time_date_timedate1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MINI_TIME_DATE_TYPE_TIMEDATE1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.timedate1", NULL);
}

/**
 * mini_time_date_timedate1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mini_time_date_timedate1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with mini_time_date_timedate1_proxy_new().
 *
 * Returns: (transfer full) (type MiniTimeDateTimedate1Proxy): The constructed proxy object or %NULL if @error is set.
 */
MiniTimeDateTimedate1 *
mini_time_date_timedate1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MINI_TIME_DATE_TIMEDATE1 (ret);
  else
    return NULL;
}

/**
 * mini_time_date_timedate1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See mini_time_date_timedate1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MiniTimeDateTimedate1Proxy): The constructed proxy object or %NULL if @error is set.
 */
MiniTimeDateTimedate1 *
mini_time_date_timedate1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MINI_TIME_DATE_TYPE_TIMEDATE1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.timedate1", NULL);
  if (ret != NULL)
    return MINI_TIME_DATE_TIMEDATE1 (ret);
  else
    return NULL;
}


/**
 * mini_time_date_timedate1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like mini_time_date_timedate1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mini_time_date_timedate1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See mini_time_date_timedate1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
mini_time_date_timedate1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MINI_TIME_DATE_TYPE_TIMEDATE1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.timedate1", NULL);
}

/**
 * mini_time_date_timedate1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mini_time_date_timedate1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with mini_time_date_timedate1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type MiniTimeDateTimedate1Proxy): The constructed proxy object or %NULL if @error is set.
 */
MiniTimeDateTimedate1 *
mini_time_date_timedate1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MINI_TIME_DATE_TIMEDATE1 (ret);
  else
    return NULL;
}

/**
 * mini_time_date_timedate1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like mini_time_date_timedate1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See mini_time_date_timedate1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MiniTimeDateTimedate1Proxy): The constructed proxy object or %NULL if @error is set.
 */
MiniTimeDateTimedate1 *
mini_time_date_timedate1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MINI_TIME_DATE_TYPE_TIMEDATE1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.timedate1", NULL);
  if (ret != NULL)
    return MINI_TIME_DATE_TIMEDATE1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * MiniTimeDateTimedate1Skeleton:
 *
 * The #MiniTimeDateTimedate1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MiniTimeDateTimedate1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MiniTimeDateTimedate1Skeleton.
 */

struct _MiniTimeDateTimedate1SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_mini_time_date_timedate1_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], MINI_TIME_DATE_TYPE_TIMEDATE1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MINI_TIME_DATE_TYPE_TIMEDATE1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_mini_time_date_timedate1_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mini_time_date_timedate1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_mini_time_date_timedate1_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mini_time_date_timedate1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _mini_time_date_timedate1_skeleton_vtable =
{
  _mini_time_date_timedate1_skeleton_handle_method_call,
  _mini_time_date_timedate1_skeleton_handle_get_property,
  _mini_time_date_timedate1_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
mini_time_date_timedate1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return mini_time_date_timedate1_interface_info ();
}

static GDBusInterfaceVTable *
mini_time_date_timedate1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_mini_time_date_timedate1_skeleton_vtable;
}

static GVariant *
mini_time_date_timedate1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_mini_time_date_timedate1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _mini_time_date_timedate1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _mini_time_date_timedate1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _mini_time_date_timedate1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.timedate1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _mini_time_date_timedate1_emit_changed (gpointer user_data);

static void
mini_time_date_timedate1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _mini_time_date_timedate1_emit_changed (skeleton);
}

static void mini_time_date_timedate1_skeleton_iface_init (MiniTimeDateTimedate1Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (MiniTimeDateTimedate1Skeleton, mini_time_date_timedate1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (MiniTimeDateTimedate1Skeleton)
                         G_IMPLEMENT_INTERFACE (MINI_TIME_DATE_TYPE_TIMEDATE1, mini_time_date_timedate1_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (MiniTimeDateTimedate1Skeleton, mini_time_date_timedate1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (MINI_TIME_DATE_TYPE_TIMEDATE1, mini_time_date_timedate1_skeleton_iface_init))

#endif
static void
mini_time_date_timedate1_skeleton_finalize (GObject *object)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  guint n;
  for (n = 0; n < 3; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (mini_time_date_timedate1_skeleton_parent_class)->finalize (object);
}

static void
mini_time_date_timedate1_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_mini_time_date_timedate1_emit_changed (gpointer user_data)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.freedesktop.timedate1",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_mini_time_date_timedate1_schedule_emit_changed (MiniTimeDateTimedate1Skeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
mini_time_date_timedate1_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _mini_time_date_timedate1_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _mini_time_date_timedate1_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
mini_time_date_timedate1_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  info = (const _ExtendedGDBusPropertyInfo *) _mini_time_date_timedate1_property_info_pointers[prop_id - 1];
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL &&
          info->emits_changed_signal)
        _mini_time_date_timedate1_schedule_emit_changed (skeleton, info, prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
mini_time_date_timedate1_skeleton_init (MiniTimeDateTimedate1Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = mini_time_date_timedate1_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, MINI_TIME_DATE_TYPE_TIMEDATE1_SKELETON, MiniTimeDateTimedate1SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 3);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_BOOLEAN);
}

static const gchar *
mini_time_date_timedate1_skeleton_get_timezone (MiniTimeDateTimedate1 *object)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
mini_time_date_timedate1_skeleton_get_local_rtc (MiniTimeDateTimedate1 *object)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
mini_time_date_timedate1_skeleton_get_ntp (MiniTimeDateTimedate1 *object)
{
  MiniTimeDateTimedate1Skeleton *skeleton = MINI_TIME_DATE_TIMEDATE1_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
mini_time_date_timedate1_skeleton_class_init (MiniTimeDateTimedate1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = mini_time_date_timedate1_skeleton_finalize;
  gobject_class->get_property = mini_time_date_timedate1_skeleton_get_property;
  gobject_class->set_property = mini_time_date_timedate1_skeleton_set_property;
  gobject_class->notify       = mini_time_date_timedate1_skeleton_notify;


  mini_time_date_timedate1_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = mini_time_date_timedate1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = mini_time_date_timedate1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = mini_time_date_timedate1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = mini_time_date_timedate1_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (MiniTimeDateTimedate1SkeletonPrivate));
#endif
}

static void
mini_time_date_timedate1_skeleton_iface_init (MiniTimeDateTimedate1Iface *iface)
{
  iface->get_timezone = mini_time_date_timedate1_skeleton_get_timezone;
  iface->get_local_rtc = mini_time_date_timedate1_skeleton_get_local_rtc;
  iface->get_ntp = mini_time_date_timedate1_skeleton_get_ntp;
}

/**
 * mini_time_date_timedate1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-timedate1.top_of_page">org.freedesktop.timedate1</link>.
 *
 * Returns: (transfer full) (type MiniTimeDateTimedate1Skeleton): The skeleton object.
 */
MiniTimeDateTimedate1 *
mini_time_date_timedate1_skeleton_new (void)
{
  return MINI_TIME_DATE_TIMEDATE1 (g_object_new (MINI_TIME_DATE_TYPE_TIMEDATE1_SKELETON, NULL));
}

